-- Optional Supabase migration for XP/Level columns and achievements table
-- Run manually in Supabase SQL editor if desired

ALTER TABLE users ADD COLUMN IF NOT EXISTS "Xp" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Level" int DEFAULT 1;

CREATE TABLE IF NOT EXISTS user_achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    achievement_key text NOT NULL,
    unlocked_at timestamptz DEFAULT now(),
    UNIQUE(username, achievement_key)
);
