-- Optional Supabase migration for XP/Level columns and achievements table.
-- Run manually in Supabase SQL editor if desired.
-- Per-user progress (QuestionStats, achievements, counters) lives in user_progress — see 003_user_progress.sql.
-- Achievement unlock rows: user_achievements (full list synced on each save) — see 004_user_achievements_index.sql.
-- Local progress/*.json is a server-side cache; Supabase is source of truth when configured.

ALTER TABLE users ADD COLUMN IF NOT EXISTS "Xp" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "Level" int DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "WeeklyCorrect" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "WeekKey" text DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS "DailyChallengeScore" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "DailyChallengeDate" text DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS "DailyCorrect" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "DayKey" text DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS "BestExamScore" int DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "BestExamCorrect" int DEFAULT 0;

CREATE TABLE IF NOT EXISTS user_achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    achievement_key text NOT NULL,
    unlocked_at timestamptz DEFAULT now(),
    UNIQUE(username, achievement_key)
);
