-- Activity feed for admin dashboard (server-only via service_role).
CREATE TABLE IF NOT EXISTS activity_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_events_created_at_idx
    ON activity_events (created_at DESC);

CREATE INDEX IF NOT EXISTS activity_events_username_idx
    ON activity_events (username);

ALTER TABLE activity_events ENABLE ROW LEVEL SECURITY;
